config/routes.rb
MobileGrid::Application.routes.draw do

  resources :runs do
    member do
      get "report"
    end
    resources :run_details,:path => "/results", :only => :show
  end


  resources :devices do
     collection do
      post "heartbeat"
     end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users

  resources :users

  match 'settings' => 'settings#show', :via => :get
  match 'settings/edit' => 'settings#edit', :via => :get
  match 'settings/update' => 'settings#update', :via => :post

end

app/models/device.rb
require 'resolv'

class Device < ActiveRecord::Base
  attr_accessible :ip, :name, :os, :device_type, :active,:vendor_id,:model
  scope :active, where(active: true)

  validates :name, :presence => true, :uniqueness => {:scope => :active}

  validates :ip, :presence => true, :uniqueness => {:scope => :active},
  :format => { :with => Resolv::IPv4::Regex }

  validates :os, :presence => true, :inclusion => { :in => %w(ios5 ios6),
    :message => "%{value} is not a valid os" }

  validates :device_type, :presence => true, :inclusion => { :in => %w(ipad iphone),
    :message => "%{value} is not a valid device type" }


  has_many :run_items
  has_many :runs, :through => :run_items


  after_initialize :init

  def init
   self.active = true if self.active.nil?
  end


  def enable
    self.active=true
    save!
  end

  def disable
    self.active=false
    save!
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  skip_before_filter :verify_authenticity_token, :only => [:heartbeat]

  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  def heartbeat
    msg = ActiveSupport::JSON.decode(params[:msg])
    msg=msg.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}
    msg[:os] = "ios"+msg[:os][0]
    msg[:device_type] = msg[:model].downcase.split(" ")[0]
    msg[:active]=true
    msg.delete(:model)

    disable_devices(msg[:ip],msg[:name])

    device = Device.find_by_vendor_id(msg[:vendor_id])
    if device.nil?
      result = Device.create(msg)
    else
      result = device.update_attributes(msg)
    end

    render :text => "#{result}"
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
  def disable_devices(ip,name)
      d=Device.find_by_ip(ip)
      d.disable unless d.nil?
      d= Device.find_by_name(name)
      d.disable unless d.nil?
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= simple_form_for(@device,:html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
    <%= f.input :name,:autofocus => true %>
    <%= f.input :ip, :required => true  %>
    <%= f.input :os, :required => true  %>
    <%= f.input :device_type, :required => true  %>
    <div class="form-actions">
        <%= f.button :submit, :class => 'btn-primary' %>
         <%= link_to 'Cancel', devices_path,:class => "btn btn-danger" %>
    </div>
<% end %>

app/views/devices/edit.html.erb
<legend>Edit Device</legend>
<%= link_to 'Back', devices_path, :class=>"pull-right" %>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<legend>Devices</legend>
<%= link_to 'New Device', new_device_path,:class=>"pull-right" %>
<div class='row'>
  <div class="span10 offset1">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Ip</th>
        <th>Os</th>
        <th>Type</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
     </thead>
     <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.ip %></td>
        <td><%= device.os %></td>
        <td><%= device.device_type %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
     </tbody>
    </table>
  </div>
</div>

app/views/devices/new.html.erb
<legend>New Device</legend>
<%= link_to 'Back', devices_path, :class=>"pull-right" %>
<div class='row'>
  <div class="span10 offset1">
    <%= render 'form' %>
  </div>
</div>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @device.name %>
</p>

<p>
  <b>Ip:</b>
  <%= @device.ip %>
</p>

<p>
  <b>Os:</b>
  <%= @device.os %>
</p>

<p>
  <b>Type:</b>
  <%= @device.device_type %>
</p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>