config/routes.rb
MobileGrid::Application.routes.draw do

  resources :runs do
    member do
      get "report"
    end
    resources :run_details,:path => "/results", :only => :show
  end


  resources :devices do
     collection do
      post "heartbeat"
     end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users

  resources :users

  match 'settings' => 'settings#show', :via => :get
  match 'settings/edit' => 'settings#edit', :via => :get
  match 'settings/update' => 'settings#update', :via => :post

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def show
    @settings = ProjectSetting.all
  end
  def edit
    @settings = ProjectSetting.all
  end
  def update
    ProjectSetting.all.each do |key,value|
      ProjectSetting[key]=params[:settings][key]
    end
    redirect_to settings_path
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/edit.html.erb
<legend>Settings</legend>

<%= simple_form_for :settings, :url => '/settings/update',:html => {:class => 'form-horizontal' } do |f| %>
  <%= f.input :project_path,input_html: { value: @settings[:project_path] } %>
  -OR-
   <%= f.input :git_url, input_html: { value: @settings[:git_url] }  %>
  <%= f.input :default_commands,input_html: { value: @settings[:default_commands] } %>

   <div class="form-actions">
      <%= f.button :submit, :class => 'btn-primary' %>
         <%= link_to 'Cancel', settings_path,:class => "btn btn-danger" %>
  </div>
<% end %>

app/views/settings/show.html.erb
<legend>Settings <small><span class='pull-right'><%= link_to 'Edit', settings_edit_path%></span></small></legend>


<div class='row'>
  <div class="span10 offset1">
    <table class="table">
      <tbody>
        <% @settings.each do |key,value| %>
        <tr>
          <td><%= key.humanize %></td>
          <td><%= value %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>