config/routes.rb
MobileGrid::Application.routes.draw do

  resources :runs do
    member do
      get "report"
    end
    resources :run_details,:path => "/results", :only => :show
  end


  resources :devices do
     collection do
      post "heartbeat"
     end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users

  resources :users

  match 'settings' => 'settings#show', :via => :get
  match 'settings/edit' => 'settings#edit', :via => :get
  match 'settings/update' => 'settings#update', :via => :post

end

app/models/run.rb
class Run < ActiveRecord::Base
  include ApplicationHelper

  default_scope order('id desc')
  attr_accessible :start_date,:run_items_attributes
  has_many :run_items
  has_many :devices, :through => :run_items
  after_initialize :init

  accepts_nested_attributes_for :run_items,:reject_if => :all_blank, :allow_destroy => true

  def name
    "Run - #{self.id}"
  end

  def init
   self.start_date ||= Time.new
  end

  def completed?
    self.run_items.all?{|item| item.completed? }
  end

  def status
   return "Running" if self.run_items.any?{|item| item.status=="Running"}
   return "Failed" if self.run_items.any?{|item| item.status=="Failed"}
   return "Passed" if self.run_items.all?{|item| item.status=="Passed"}
   return "Completed" if self.run_items.all?{|item| item.status=="Completed" || item.status=="Skipped"}
   return "Not Started"
  end

  after_create do |run|
    if git?
      Delayed::Job.enqueue GitJob.new(run.id)
    end
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  # GET /runs
  # GET /runs.json
  def index
    @runs = Run.page(params[:page]).per(10).includes(:run_items)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @runs }
    end
  end

  def report
     @run = Run.find(params[:id],:include => {:run_items => [:device, {:features => :scenarios}]})
     unless @run.completed?
      redirect_to @run, notice: 'Run is not completed..'
      return
     end
  end
  # GET /runs/1
  # GET /runs/1.json
  def show
    @run = Run.find(params[:id],:include => {:run_items => [:device, :scenarios]})

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @run }
      format.js
    end
  end

  # GET /runs/new
  # GET /runs/new.json
  def new
    @run = Run.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @run }
    end
  end


  # POST /runs
  # POST /runs.json
  def create
    devices = params[:run][:device_ids]
    params[:run].delete(:device_ids)
    @run = Run.new(params[:run])

    unless devices.any? {|d| not d.to_s.empty?}
      respond_to do |format|
        format.html {
          flash[:error]='There are no devices selected.'
          redirect_to action: "new"
        }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
      return
    end

    devices.each do |d_id|
      @run.run_items << RunItem.new(:device_id => d_id) unless d_id.empty?
    end

    @run.run_items
    respond_to do |format|
      if @run.save
        format.html { redirect_to @run}
        format.json { render json: @run, status: :created, location: @run }
      else
        format.html { render action: "new" }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run = Run.find(params[:id])
    @run.destroy

    respond_to do |format|
      format.html { redirect_to runs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/runs_helper.rb
module RunsHelper
  def convert_status(status)
    stat=""
    if status.downcase == "passed"
     stat="icon-ok green"
    elsif status.downcase == "failed"
      stat="icon-remove red"
    else
      stat="icon-circle-blank blue"
    end

    content_tag(:i, "", :class=>stat)
  end

  def completed?(run)
    run.run_items.all? {|r| r.completed?}
  end

end

app/views/runs/_device.html.erb
<tr>
        <td><%= link_to device.device.name, run_run_detail_path(@run,device) %></td>
        <td><% if(device.status=="Running") %> <%= content_tag(:i," ",:class => "icon-refresh icon-spin") %> <% end %><%= display_status(device.status) %></td>
        <td>
         <small>
         Total : <span class="badge"><%= device.scenarios.size %></span> |
         Passed : <span class="badge badge-success"> <%= device.scenarios.select {|s| s.status == "passed"}.length %> </span> |
         Failed : <span class="badge badge-important"><%= device.scenarios.select {|s| s.status == "failed"}.length %> </span>|
         Skipped : <span class="badge badge-info"><%= device.scenarios.select {|s| s.status == "skipped"}.length %> </span>
      </small>
        </td>
      </tr>

app/views/runs/_form.html.erb
<%= simple_form_for(@run,:html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

<!--   <div class="form-inputs">
    <%= f.input :start_date %>
  </div>
 -->

  <%= f.association :devices, as: :check_boxes, label: 'Select devices:', collection: Device.active.all(order: 'name') %>


  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to 'Cancel', runs_path,:class => "btn btn-danger" %>
  </div>

<% end %>

app/views/runs/index.html.erb
<legend>Runs</legend>
<%= link_to 'New Run', new_run_path,:class=>"pull-right" %>
<div class='row'>
  <div class="span10 offset1">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Run Name</th>
          <th>Status</th>
          <th>Devices</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
    <% @runs.each do |run| %>
      <tr>
        <td><%= link_to run.name, run %></td>
        <td><%= display_status(run.status) %></td>
        <td><%= run.run_items.size %></td>
        <td><%= link_to ' ', run, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "icon-trash"  %></td>
      </tr>
    <% end %>
    </tbody>
    </table>
    <%= paginate @runs %>
  </div>
</div>

app/views/runs/new.html.erb
<legend>New Run</legend>

<%= render 'form' %>

app/views/runs/report.html.erb
<legend>Report  <small> &nbsp;<%= link_to @run.name, run_path(@run) %></small> </legend>
<div class='row'>
  <div class="span10 offset1">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th></th>
          <% @run.run_items.each do |run_item| %>
            <th><%= run_item.device.name %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @run.run_items[0].features.each_with_index do |feature,feature_index| %>
          <tr>
            <td class='feature'><%= feature.name %></td>
              <% @run.run_items.length.times do  %>
                <td></td>
              <% end %>
          </tr>
          <% feature.scenarios.each_with_index do |scenario,index| %>
            <tr>
              <td class='scenario'><%= scenario.name %></td>
               <% @run.run_items.each do |run_item| %>
                <td><%= convert_status(run_item.features[feature_index].scenarios[index].status) %></td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/runs/show.html.erb
<legend><%= @run.name %></legend>
<span ><i class='icon-bar-chart'></i> <%= link_to 'Report', report_run_path(@run)%></span>
<%= link_to 'Back', runs_path, :class=>"pull-right"%>
<div class='row'>
  <div class="span10 offset1">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Device Name</th>
          <th>Status</th>
          <th>Count</th>
        </tr>
      </thead>
      <tbody id='device_details'>
        <%= render partial: "device", collection: @run.run_items %>
      </tbody>
    </table>
  </div>
</div>


<% unless completed?(@run) %>
  <%= javascript_tag do -%>
  $(document).ready(
    function(){
      setInterval(function(){
        $.ajax({
          url: "<%= run_path(@run) %>",
          type: "GET",
          dataType: "script"
      });
    }, 4000 );
  });
  <% end -%>
<% end -%>

app/views/runs/show.js.erb
$("#device_details").html("<%= escape_javascript(render(:partial => 'device', :collection => @run.run_items)).html_safe %>");