config/routes.rb
MobileGrid::Application.routes.draw do

  resources :runs do
    member do
      get "report"
    end
    resources :run_details,:path => "/results", :only => :show
  end


  resources :devices do
     collection do
      post "heartbeat"
     end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users

  resources :users

  match 'settings' => 'settings#show', :via => :get
  match 'settings/edit' => 'settings#edit', :via => :get
  match 'settings/update' => 'settings#update', :via => :post

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Mobile Grid", root_path, :class => 'brand' %>
<p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Welcome <%= current_user.name %> | <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
  <% else %>
   <!-- <%= link_to 'Login', new_user_session_path %> -->
  <% end %>
</p>
<ul class="nav">
  <%= nav_link 'Dashboard', root_path %>
  <%= nav_link 'Runs', runs_path %>
  <%= nav_link 'Devices', devices_path %>
  <%= nav_link 'Settings', settings_path %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mobile Grid" %></title>
    <meta charset='utf-8'>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mobile Grid" %>">
    <!-- <link href="//netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
     <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdn.oesmith.co.uk/morris-0.4.2.min.js"></script>  -->
     <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <!-- <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.2.min.css"> -->
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>